-- sqlplus / as sysdba @/docker-entrypoint-initdb.d/create-pdb-users.sql

ALTER SYSTEM SET db_create_file_dest = '/opt/oracle/oradata' SCOPE=SPFILE;
SHUTDOWN IMMEDIATE;
STARTUP;

-- Crearea unui PDB pentru OLTP
CREATE PLUGGABLE DATABASE oltp ADMIN USER admin IDENTIFIED BY admin;
ALTER PLUGGABLE DATABASE oltp OPEN;

-- Crearea de PDB-uri pentru servere
CREATE PLUGGABLE DATABASE nord ADMIN USER admin IDENTIFIED BY admin;
ALTER PLUGGABLE DATABASE nord OPEN;

CREATE PLUGGABLE DATABASE sud ADMIN USER admin IDENTIFIED BY admin;
ALTER PLUGGABLE DATABASE sud OPEN;

CREATE PLUGGABLE DATABASE central ADMIN USER admin IDENTIFIED BY admin;
ALTER PLUGGABLE DATABASE central OPEN;

CREATE PLUGGABLE DATABASE arhiva ADMIN USER admin IDENTIFIED BY admin;
ALTER PLUGGABLE DATABASE arhiva OPEN;


ALTER SESSION SET CONTAINER = oltp;
GRANT ALL PRIVILEGES TO admin;

ALTER SESSION SET CONTAINER = nord;
GRANT ALL PRIVILEGES TO admin;

ALTER SESSION SET CONTAINER = sud;
GRANT ALL PRIVILEGES TO admin;

ALTER SESSION SET CONTAINER = central;
GRANT ALL PRIVILEGES TO admin;

ALTER SESSION SET CONTAINER = arhiva;
GRANT ALL PRIVILEGES TO admin;